name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: |
            yarn.lock
      - run: yarn install --immutable

      - run: yarn lint
      - run: yarn test